# Generated by Django 6.0.6 on 2026-07-10 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("paid", "Pago"),
                    ("canceled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
